### ISSUE TITLE
Improve SQL using Debugbar

### ISSUE THREAD

**Issue by Kenji-jp** [Kenji-jp/laraevel-sns_github#10]
#ToDo
- [ ] install Debugbar
- [ ] learn a [ N + 1 problem ]
- [ ] improve Article List
- [ ] improve Liked Article List
- [ ] improve follower's Article List
- [ ] improve followee's Article List
- [ ] improve follower
