### ISSUE TITLE
Create Follow function and User function

### ISSUE THREAD

**Issue by Kenji-jp** [Kenji-jp/laraevel-sns_github#9]
# ToDo
- [ ] create UserController
- [ ] configure Google and Laravel
- [ ] install Laravel Sociallite
- [ ] redirect to Google
- [ ] login using Google account
- [ ] To register form if dont have account.
- [ ] show the Google to register btn
